PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX db:   <http://bio2rdf.org/drugbank_vocabulary:>
SELECT ?drug_name ?dosage_predicates ?indication
WHERE { ?drug rdf:type   db:Drug    .
    	?drug rdfs:label ?drug_name .
    	OPTIONAL {  ?drug db:dosage     ?do       .
                    ?do   rdfs:label    ?dosage   . }
        OPTIONAL {  ?drug db:indication ?ind      .
                    ?ind  rdfs:label    ?indication }
} LIMIT 10
